### ISSUE TITLE
Credits page update

### ISSUE THREAD

**Issue by VictoriaMeldrum** [BallStateCBER/conexus#4]
On this page... https://github.com/BallStateCBER 

• Change Center for Business and Economic Research link to www.bsu.edu/cber 
• Ball State link is good
• Add a new line with "Contact CBER at cber@bsu.edu" (I know this is redundant with our footer info, but ppl don't read carefully)

**Comment by PhantomWatson** [comment]
Donezo.

**Comment by VictoriaMeldrum** [comment]
Except we need some contact info! How about this line:
"For media inquiries, please contact Michael Hicks or Srikant Devaraj at 765-285-5926 (9 a.m.–5 p.m. Eastern Time) or email cberdirector@bsu.edu."

**Comment by PhantomWatson** [comment]
The current bio line is at 137 characters and has a maximum of 140 characters. :(
